sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "102311243"
  alioss:
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    bucket-name: zephyr-0131


